/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTailorsRouteImport } from './routes/dashboard/tailors'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardMeasurementsRouteImport } from './routes/dashboard/measurements'
import { Route as DashboardCreateRouteImport } from './routes/dashboard/create'
import { Route as DashboardWalletIndexRouteImport } from './routes/dashboard/wallet/index'
import { Route as DashboardOrdersIndexRouteImport } from './routes/dashboard/orders/index'
import { Route as DashboardExploreIndexRouteImport } from './routes/dashboard/explore/index'
import { Route as DashboardWalletWithdrawRouteImport } from './routes/dashboard/wallet/withdraw'
import { Route as DashboardWalletTopupRouteImport } from './routes/dashboard/wallet/topup'
import { Route as DashboardWalletSpendingRouteImport } from './routes/dashboard/wallet/spending'
import { Route as DashboardWalletWithdrawIndexRouteImport } from './routes/dashboard/wallet/withdraw.index'
import { Route as DashboardWalletTopupIndexRouteImport } from './routes/dashboard/wallet/topup.index'
import { Route as DashboardOrdersOrderIdIndexRouteImport } from './routes/dashboard/orders/$orderId/index'
import { Route as DashboardWalletWithdrawSuccessRouteImport } from './routes/dashboard/wallet/withdraw.success'
import { Route as DashboardWalletWithdrawAddBankRouteImport } from './routes/dashboard/wallet/withdraw.add-bank'
import { Route as DashboardWalletTransactionTransactionIdRouteImport } from './routes/dashboard/wallet/transaction.$transactionId'
import { Route as DashboardWalletTopupSuccessRouteImport } from './routes/dashboard/wallet/topup.success'
import { Route as DashboardOrdersOrderIdRateRouteImport } from './routes/dashboard/orders/$orderId/rate'
import { Route as DashboardOrdersOrderIdPayRouteImport } from './routes/dashboard/orders/$orderId/pay'
import { Route as DashboardOrdersOrderIdFabricRouteImport } from './routes/dashboard/orders/$orderId/fabric'
import { Route as DashboardOrdersOrderIdAcknowledgeRouteImport } from './routes/dashboard/orders/$orderId/acknowledge'
import { Route as DashboardExploreMerchantMerchantIdIndexRouteImport } from './routes/dashboard/explore/merchant.$merchantId.index'
import { Route as DashboardWalletWithdrawAddBankSuccessRouteImport } from './routes/dashboard/wallet/withdraw.add-bank.success'
import { Route as DashboardExploreMerchantMerchantIdTailorsRouteImport } from './routes/dashboard/explore/merchant.$merchantId.tailors'
import { Route as DashboardExploreMerchantMerchantIdSuccessRouteImport } from './routes/dashboard/explore/merchant.$merchantId.success'
import { Route as DashboardExploreMerchantMerchantIdReviewRouteImport } from './routes/dashboard/explore/merchant.$merchantId.review'
import { Route as DashboardExploreMerchantMerchantIdPayRouteImport } from './routes/dashboard/explore/merchant.$merchantId.pay'
import { Route as DashboardExploreMerchantMerchantIdChatRouteImport } from './routes/dashboard/explore/merchant.$merchantId.chat'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTailorsRoute = DashboardTailorsRouteImport.update({
  id: '/tailors',
  path: '/tailors',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMeasurementsRoute = DashboardMeasurementsRouteImport.update({
  id: '/measurements',
  path: '/measurements',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCreateRoute = DashboardCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWalletIndexRoute = DashboardWalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardExploreIndexRoute = DashboardExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWalletWithdrawRoute = DashboardWalletWithdrawRouteImport.update({
  id: '/wallet/withdraw',
  path: '/wallet/withdraw',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWalletTopupRoute = DashboardWalletTopupRouteImport.update({
  id: '/wallet/topup',
  path: '/wallet/topup',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWalletSpendingRoute = DashboardWalletSpendingRouteImport.update({
  id: '/wallet/spending',
  path: '/wallet/spending',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWalletWithdrawIndexRoute =
  DashboardWalletWithdrawIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardWalletWithdrawRoute,
  } as any)
const DashboardWalletTopupIndexRoute =
  DashboardWalletTopupIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardWalletTopupRoute,
  } as any)
const DashboardOrdersOrderIdIndexRoute =
  DashboardOrdersOrderIdIndexRouteImport.update({
    id: '/orders/$orderId/',
    path: '/orders/$orderId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardWalletWithdrawSuccessRoute =
  DashboardWalletWithdrawSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => DashboardWalletWithdrawRoute,
  } as any)
const DashboardWalletWithdrawAddBankRoute =
  DashboardWalletWithdrawAddBankRouteImport.update({
    id: '/add-bank',
    path: '/add-bank',
    getParentRoute: () => DashboardWalletWithdrawRoute,
  } as any)
const DashboardWalletTransactionTransactionIdRoute =
  DashboardWalletTransactionTransactionIdRouteImport.update({
    id: '/wallet/transaction/$transactionId',
    path: '/wallet/transaction/$transactionId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardWalletTopupSuccessRoute =
  DashboardWalletTopupSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => DashboardWalletTopupRoute,
  } as any)
const DashboardOrdersOrderIdRateRoute =
  DashboardOrdersOrderIdRateRouteImport.update({
    id: '/orders/$orderId/rate',
    path: '/orders/$orderId/rate',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOrdersOrderIdPayRoute =
  DashboardOrdersOrderIdPayRouteImport.update({
    id: '/orders/$orderId/pay',
    path: '/orders/$orderId/pay',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOrdersOrderIdFabricRoute =
  DashboardOrdersOrderIdFabricRouteImport.update({
    id: '/orders/$orderId/fabric',
    path: '/orders/$orderId/fabric',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOrdersOrderIdAcknowledgeRoute =
  DashboardOrdersOrderIdAcknowledgeRouteImport.update({
    id: '/orders/$orderId/acknowledge',
    path: '/orders/$orderId/acknowledge',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardExploreMerchantMerchantIdIndexRoute =
  DashboardExploreMerchantMerchantIdIndexRouteImport.update({
    id: '/explore/merchant/$merchantId/',
    path: '/explore/merchant/$merchantId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardWalletWithdrawAddBankSuccessRoute =
  DashboardWalletWithdrawAddBankSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => DashboardWalletWithdrawAddBankRoute,
  } as any)
const DashboardExploreMerchantMerchantIdTailorsRoute =
  DashboardExploreMerchantMerchantIdTailorsRouteImport.update({
    id: '/explore/merchant/$merchantId/tailors',
    path: '/explore/merchant/$merchantId/tailors',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardExploreMerchantMerchantIdSuccessRoute =
  DashboardExploreMerchantMerchantIdSuccessRouteImport.update({
    id: '/explore/merchant/$merchantId/success',
    path: '/explore/merchant/$merchantId/success',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardExploreMerchantMerchantIdReviewRoute =
  DashboardExploreMerchantMerchantIdReviewRouteImport.update({
    id: '/explore/merchant/$merchantId/review',
    path: '/explore/merchant/$merchantId/review',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardExploreMerchantMerchantIdPayRoute =
  DashboardExploreMerchantMerchantIdPayRouteImport.update({
    id: '/explore/merchant/$merchantId/pay',
    path: '/explore/merchant/$merchantId/pay',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardExploreMerchantMerchantIdChatRoute =
  DashboardExploreMerchantMerchantIdChatRouteImport.update({
    id: '/explore/merchant/$merchantId/chat',
    path: '/explore/merchant/$merchantId/chat',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/measurements': typeof DashboardMeasurementsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tailors': typeof DashboardTailorsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/wallet/spending': typeof DashboardWalletSpendingRoute
  '/dashboard/wallet/topup': typeof DashboardWalletTopupRouteWithChildren
  '/dashboard/wallet/withdraw': typeof DashboardWalletWithdrawRouteWithChildren
  '/dashboard/explore/': typeof DashboardExploreIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/wallet/': typeof DashboardWalletIndexRoute
  '/dashboard/orders/$orderId/acknowledge': typeof DashboardOrdersOrderIdAcknowledgeRoute
  '/dashboard/orders/$orderId/fabric': typeof DashboardOrdersOrderIdFabricRoute
  '/dashboard/orders/$orderId/pay': typeof DashboardOrdersOrderIdPayRoute
  '/dashboard/orders/$orderId/rate': typeof DashboardOrdersOrderIdRateRoute
  '/dashboard/wallet/topup/success': typeof DashboardWalletTopupSuccessRoute
  '/dashboard/wallet/transaction/$transactionId': typeof DashboardWalletTransactionTransactionIdRoute
  '/dashboard/wallet/withdraw/add-bank': typeof DashboardWalletWithdrawAddBankRouteWithChildren
  '/dashboard/wallet/withdraw/success': typeof DashboardWalletWithdrawSuccessRoute
  '/dashboard/orders/$orderId/': typeof DashboardOrdersOrderIdIndexRoute
  '/dashboard/wallet/topup/': typeof DashboardWalletTopupIndexRoute
  '/dashboard/wallet/withdraw/': typeof DashboardWalletWithdrawIndexRoute
  '/dashboard/explore/merchant/$merchantId/chat': typeof DashboardExploreMerchantMerchantIdChatRoute
  '/dashboard/explore/merchant/$merchantId/pay': typeof DashboardExploreMerchantMerchantIdPayRoute
  '/dashboard/explore/merchant/$merchantId/review': typeof DashboardExploreMerchantMerchantIdReviewRoute
  '/dashboard/explore/merchant/$merchantId/success': typeof DashboardExploreMerchantMerchantIdSuccessRoute
  '/dashboard/explore/merchant/$merchantId/tailors': typeof DashboardExploreMerchantMerchantIdTailorsRoute
  '/dashboard/wallet/withdraw/add-bank/success': typeof DashboardWalletWithdrawAddBankSuccessRoute
  '/dashboard/explore/merchant/$merchantId/': typeof DashboardExploreMerchantMerchantIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/measurements': typeof DashboardMeasurementsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tailors': typeof DashboardTailorsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/wallet/spending': typeof DashboardWalletSpendingRoute
  '/dashboard/explore': typeof DashboardExploreIndexRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/wallet': typeof DashboardWalletIndexRoute
  '/dashboard/orders/$orderId/acknowledge': typeof DashboardOrdersOrderIdAcknowledgeRoute
  '/dashboard/orders/$orderId/fabric': typeof DashboardOrdersOrderIdFabricRoute
  '/dashboard/orders/$orderId/pay': typeof DashboardOrdersOrderIdPayRoute
  '/dashboard/orders/$orderId/rate': typeof DashboardOrdersOrderIdRateRoute
  '/dashboard/wallet/topup/success': typeof DashboardWalletTopupSuccessRoute
  '/dashboard/wallet/transaction/$transactionId': typeof DashboardWalletTransactionTransactionIdRoute
  '/dashboard/wallet/withdraw/add-bank': typeof DashboardWalletWithdrawAddBankRouteWithChildren
  '/dashboard/wallet/withdraw/success': typeof DashboardWalletWithdrawSuccessRoute
  '/dashboard/orders/$orderId': typeof DashboardOrdersOrderIdIndexRoute
  '/dashboard/wallet/topup': typeof DashboardWalletTopupIndexRoute
  '/dashboard/wallet/withdraw': typeof DashboardWalletWithdrawIndexRoute
  '/dashboard/explore/merchant/$merchantId/chat': typeof DashboardExploreMerchantMerchantIdChatRoute
  '/dashboard/explore/merchant/$merchantId/pay': typeof DashboardExploreMerchantMerchantIdPayRoute
  '/dashboard/explore/merchant/$merchantId/review': typeof DashboardExploreMerchantMerchantIdReviewRoute
  '/dashboard/explore/merchant/$merchantId/success': typeof DashboardExploreMerchantMerchantIdSuccessRoute
  '/dashboard/explore/merchant/$merchantId/tailors': typeof DashboardExploreMerchantMerchantIdTailorsRoute
  '/dashboard/wallet/withdraw/add-bank/success': typeof DashboardWalletWithdrawAddBankSuccessRoute
  '/dashboard/explore/merchant/$merchantId': typeof DashboardExploreMerchantMerchantIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/measurements': typeof DashboardMeasurementsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tailors': typeof DashboardTailorsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/wallet/spending': typeof DashboardWalletSpendingRoute
  '/dashboard/wallet/topup': typeof DashboardWalletTopupRouteWithChildren
  '/dashboard/wallet/withdraw': typeof DashboardWalletWithdrawRouteWithChildren
  '/dashboard/explore/': typeof DashboardExploreIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/wallet/': typeof DashboardWalletIndexRoute
  '/dashboard/orders/$orderId/acknowledge': typeof DashboardOrdersOrderIdAcknowledgeRoute
  '/dashboard/orders/$orderId/fabric': typeof DashboardOrdersOrderIdFabricRoute
  '/dashboard/orders/$orderId/pay': typeof DashboardOrdersOrderIdPayRoute
  '/dashboard/orders/$orderId/rate': typeof DashboardOrdersOrderIdRateRoute
  '/dashboard/wallet/topup/success': typeof DashboardWalletTopupSuccessRoute
  '/dashboard/wallet/transaction/$transactionId': typeof DashboardWalletTransactionTransactionIdRoute
  '/dashboard/wallet/withdraw/add-bank': typeof DashboardWalletWithdrawAddBankRouteWithChildren
  '/dashboard/wallet/withdraw/success': typeof DashboardWalletWithdrawSuccessRoute
  '/dashboard/orders/$orderId/': typeof DashboardOrdersOrderIdIndexRoute
  '/dashboard/wallet/topup/': typeof DashboardWalletTopupIndexRoute
  '/dashboard/wallet/withdraw/': typeof DashboardWalletWithdrawIndexRoute
  '/dashboard/explore/merchant/$merchantId/chat': typeof DashboardExploreMerchantMerchantIdChatRoute
  '/dashboard/explore/merchant/$merchantId/pay': typeof DashboardExploreMerchantMerchantIdPayRoute
  '/dashboard/explore/merchant/$merchantId/review': typeof DashboardExploreMerchantMerchantIdReviewRoute
  '/dashboard/explore/merchant/$merchantId/success': typeof DashboardExploreMerchantMerchantIdSuccessRoute
  '/dashboard/explore/merchant/$merchantId/tailors': typeof DashboardExploreMerchantMerchantIdTailorsRoute
  '/dashboard/wallet/withdraw/add-bank/success': typeof DashboardWalletWithdrawAddBankSuccessRoute
  '/dashboard/explore/merchant/$merchantId/': typeof DashboardExploreMerchantMerchantIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/create'
    | '/dashboard/measurements'
    | '/dashboard/settings'
    | '/dashboard/tailors'
    | '/dashboard/'
    | '/dashboard/wallet/spending'
    | '/dashboard/wallet/topup'
    | '/dashboard/wallet/withdraw'
    | '/dashboard/explore/'
    | '/dashboard/orders/'
    | '/dashboard/wallet/'
    | '/dashboard/orders/$orderId/acknowledge'
    | '/dashboard/orders/$orderId/fabric'
    | '/dashboard/orders/$orderId/pay'
    | '/dashboard/orders/$orderId/rate'
    | '/dashboard/wallet/topup/success'
    | '/dashboard/wallet/transaction/$transactionId'
    | '/dashboard/wallet/withdraw/add-bank'
    | '/dashboard/wallet/withdraw/success'
    | '/dashboard/orders/$orderId/'
    | '/dashboard/wallet/topup/'
    | '/dashboard/wallet/withdraw/'
    | '/dashboard/explore/merchant/$merchantId/chat'
    | '/dashboard/explore/merchant/$merchantId/pay'
    | '/dashboard/explore/merchant/$merchantId/review'
    | '/dashboard/explore/merchant/$merchantId/success'
    | '/dashboard/explore/merchant/$merchantId/tailors'
    | '/dashboard/wallet/withdraw/add-bank/success'
    | '/dashboard/explore/merchant/$merchantId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/create'
    | '/dashboard/measurements'
    | '/dashboard/settings'
    | '/dashboard/tailors'
    | '/dashboard'
    | '/dashboard/wallet/spending'
    | '/dashboard/explore'
    | '/dashboard/orders'
    | '/dashboard/wallet'
    | '/dashboard/orders/$orderId/acknowledge'
    | '/dashboard/orders/$orderId/fabric'
    | '/dashboard/orders/$orderId/pay'
    | '/dashboard/orders/$orderId/rate'
    | '/dashboard/wallet/topup/success'
    | '/dashboard/wallet/transaction/$transactionId'
    | '/dashboard/wallet/withdraw/add-bank'
    | '/dashboard/wallet/withdraw/success'
    | '/dashboard/orders/$orderId'
    | '/dashboard/wallet/topup'
    | '/dashboard/wallet/withdraw'
    | '/dashboard/explore/merchant/$merchantId/chat'
    | '/dashboard/explore/merchant/$merchantId/pay'
    | '/dashboard/explore/merchant/$merchantId/review'
    | '/dashboard/explore/merchant/$merchantId/success'
    | '/dashboard/explore/merchant/$merchantId/tailors'
    | '/dashboard/wallet/withdraw/add-bank/success'
    | '/dashboard/explore/merchant/$merchantId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/create'
    | '/dashboard/measurements'
    | '/dashboard/settings'
    | '/dashboard/tailors'
    | '/dashboard/'
    | '/dashboard/wallet/spending'
    | '/dashboard/wallet/topup'
    | '/dashboard/wallet/withdraw'
    | '/dashboard/explore/'
    | '/dashboard/orders/'
    | '/dashboard/wallet/'
    | '/dashboard/orders/$orderId/acknowledge'
    | '/dashboard/orders/$orderId/fabric'
    | '/dashboard/orders/$orderId/pay'
    | '/dashboard/orders/$orderId/rate'
    | '/dashboard/wallet/topup/success'
    | '/dashboard/wallet/transaction/$transactionId'
    | '/dashboard/wallet/withdraw/add-bank'
    | '/dashboard/wallet/withdraw/success'
    | '/dashboard/orders/$orderId/'
    | '/dashboard/wallet/topup/'
    | '/dashboard/wallet/withdraw/'
    | '/dashboard/explore/merchant/$merchantId/chat'
    | '/dashboard/explore/merchant/$merchantId/pay'
    | '/dashboard/explore/merchant/$merchantId/review'
    | '/dashboard/explore/merchant/$merchantId/success'
    | '/dashboard/explore/merchant/$merchantId/tailors'
    | '/dashboard/wallet/withdraw/add-bank/success'
    | '/dashboard/explore/merchant/$merchantId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tailors': {
      id: '/dashboard/tailors'
      path: '/tailors'
      fullPath: '/dashboard/tailors'
      preLoaderRoute: typeof DashboardTailorsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/measurements': {
      id: '/dashboard/measurements'
      path: '/measurements'
      fullPath: '/dashboard/measurements'
      preLoaderRoute: typeof DashboardMeasurementsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/create': {
      id: '/dashboard/create'
      path: '/create'
      fullPath: '/dashboard/create'
      preLoaderRoute: typeof DashboardCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/wallet/': {
      id: '/dashboard/wallet/'
      path: '/wallet'
      fullPath: '/dashboard/wallet/'
      preLoaderRoute: typeof DashboardWalletIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders/': {
      id: '/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/explore/': {
      id: '/dashboard/explore/'
      path: '/explore'
      fullPath: '/dashboard/explore/'
      preLoaderRoute: typeof DashboardExploreIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/wallet/withdraw': {
      id: '/dashboard/wallet/withdraw'
      path: '/wallet/withdraw'
      fullPath: '/dashboard/wallet/withdraw'
      preLoaderRoute: typeof DashboardWalletWithdrawRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/wallet/topup': {
      id: '/dashboard/wallet/topup'
      path: '/wallet/topup'
      fullPath: '/dashboard/wallet/topup'
      preLoaderRoute: typeof DashboardWalletTopupRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/wallet/spending': {
      id: '/dashboard/wallet/spending'
      path: '/wallet/spending'
      fullPath: '/dashboard/wallet/spending'
      preLoaderRoute: typeof DashboardWalletSpendingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/wallet/withdraw/': {
      id: '/dashboard/wallet/withdraw/'
      path: '/'
      fullPath: '/dashboard/wallet/withdraw/'
      preLoaderRoute: typeof DashboardWalletWithdrawIndexRouteImport
      parentRoute: typeof DashboardWalletWithdrawRoute
    }
    '/dashboard/wallet/topup/': {
      id: '/dashboard/wallet/topup/'
      path: '/'
      fullPath: '/dashboard/wallet/topup/'
      preLoaderRoute: typeof DashboardWalletTopupIndexRouteImport
      parentRoute: typeof DashboardWalletTopupRoute
    }
    '/dashboard/orders/$orderId/': {
      id: '/dashboard/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/dashboard/orders/$orderId/'
      preLoaderRoute: typeof DashboardOrdersOrderIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/wallet/withdraw/success': {
      id: '/dashboard/wallet/withdraw/success'
      path: '/success'
      fullPath: '/dashboard/wallet/withdraw/success'
      preLoaderRoute: typeof DashboardWalletWithdrawSuccessRouteImport
      parentRoute: typeof DashboardWalletWithdrawRoute
    }
    '/dashboard/wallet/withdraw/add-bank': {
      id: '/dashboard/wallet/withdraw/add-bank'
      path: '/add-bank'
      fullPath: '/dashboard/wallet/withdraw/add-bank'
      preLoaderRoute: typeof DashboardWalletWithdrawAddBankRouteImport
      parentRoute: typeof DashboardWalletWithdrawRoute
    }
    '/dashboard/wallet/transaction/$transactionId': {
      id: '/dashboard/wallet/transaction/$transactionId'
      path: '/wallet/transaction/$transactionId'
      fullPath: '/dashboard/wallet/transaction/$transactionId'
      preLoaderRoute: typeof DashboardWalletTransactionTransactionIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/wallet/topup/success': {
      id: '/dashboard/wallet/topup/success'
      path: '/success'
      fullPath: '/dashboard/wallet/topup/success'
      preLoaderRoute: typeof DashboardWalletTopupSuccessRouteImport
      parentRoute: typeof DashboardWalletTopupRoute
    }
    '/dashboard/orders/$orderId/rate': {
      id: '/dashboard/orders/$orderId/rate'
      path: '/orders/$orderId/rate'
      fullPath: '/dashboard/orders/$orderId/rate'
      preLoaderRoute: typeof DashboardOrdersOrderIdRateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders/$orderId/pay': {
      id: '/dashboard/orders/$orderId/pay'
      path: '/orders/$orderId/pay'
      fullPath: '/dashboard/orders/$orderId/pay'
      preLoaderRoute: typeof DashboardOrdersOrderIdPayRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders/$orderId/fabric': {
      id: '/dashboard/orders/$orderId/fabric'
      path: '/orders/$orderId/fabric'
      fullPath: '/dashboard/orders/$orderId/fabric'
      preLoaderRoute: typeof DashboardOrdersOrderIdFabricRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders/$orderId/acknowledge': {
      id: '/dashboard/orders/$orderId/acknowledge'
      path: '/orders/$orderId/acknowledge'
      fullPath: '/dashboard/orders/$orderId/acknowledge'
      preLoaderRoute: typeof DashboardOrdersOrderIdAcknowledgeRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/explore/merchant/$merchantId/': {
      id: '/dashboard/explore/merchant/$merchantId/'
      path: '/explore/merchant/$merchantId'
      fullPath: '/dashboard/explore/merchant/$merchantId/'
      preLoaderRoute: typeof DashboardExploreMerchantMerchantIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/wallet/withdraw/add-bank/success': {
      id: '/dashboard/wallet/withdraw/add-bank/success'
      path: '/success'
      fullPath: '/dashboard/wallet/withdraw/add-bank/success'
      preLoaderRoute: typeof DashboardWalletWithdrawAddBankSuccessRouteImport
      parentRoute: typeof DashboardWalletWithdrawAddBankRoute
    }
    '/dashboard/explore/merchant/$merchantId/tailors': {
      id: '/dashboard/explore/merchant/$merchantId/tailors'
      path: '/explore/merchant/$merchantId/tailors'
      fullPath: '/dashboard/explore/merchant/$merchantId/tailors'
      preLoaderRoute: typeof DashboardExploreMerchantMerchantIdTailorsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/explore/merchant/$merchantId/success': {
      id: '/dashboard/explore/merchant/$merchantId/success'
      path: '/explore/merchant/$merchantId/success'
      fullPath: '/dashboard/explore/merchant/$merchantId/success'
      preLoaderRoute: typeof DashboardExploreMerchantMerchantIdSuccessRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/explore/merchant/$merchantId/review': {
      id: '/dashboard/explore/merchant/$merchantId/review'
      path: '/explore/merchant/$merchantId/review'
      fullPath: '/dashboard/explore/merchant/$merchantId/review'
      preLoaderRoute: typeof DashboardExploreMerchantMerchantIdReviewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/explore/merchant/$merchantId/pay': {
      id: '/dashboard/explore/merchant/$merchantId/pay'
      path: '/explore/merchant/$merchantId/pay'
      fullPath: '/dashboard/explore/merchant/$merchantId/pay'
      preLoaderRoute: typeof DashboardExploreMerchantMerchantIdPayRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/explore/merchant/$merchantId/chat': {
      id: '/dashboard/explore/merchant/$merchantId/chat'
      path: '/explore/merchant/$merchantId/chat'
      fullPath: '/dashboard/explore/merchant/$merchantId/chat'
      preLoaderRoute: typeof DashboardExploreMerchantMerchantIdChatRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardWalletTopupRouteChildren {
  DashboardWalletTopupSuccessRoute: typeof DashboardWalletTopupSuccessRoute
  DashboardWalletTopupIndexRoute: typeof DashboardWalletTopupIndexRoute
}

const DashboardWalletTopupRouteChildren: DashboardWalletTopupRouteChildren = {
  DashboardWalletTopupSuccessRoute: DashboardWalletTopupSuccessRoute,
  DashboardWalletTopupIndexRoute: DashboardWalletTopupIndexRoute,
}

const DashboardWalletTopupRouteWithChildren =
  DashboardWalletTopupRoute._addFileChildren(DashboardWalletTopupRouteChildren)

interface DashboardWalletWithdrawAddBankRouteChildren {
  DashboardWalletWithdrawAddBankSuccessRoute: typeof DashboardWalletWithdrawAddBankSuccessRoute
}

const DashboardWalletWithdrawAddBankRouteChildren: DashboardWalletWithdrawAddBankRouteChildren =
  {
    DashboardWalletWithdrawAddBankSuccessRoute:
      DashboardWalletWithdrawAddBankSuccessRoute,
  }

const DashboardWalletWithdrawAddBankRouteWithChildren =
  DashboardWalletWithdrawAddBankRoute._addFileChildren(
    DashboardWalletWithdrawAddBankRouteChildren,
  )

interface DashboardWalletWithdrawRouteChildren {
  DashboardWalletWithdrawAddBankRoute: typeof DashboardWalletWithdrawAddBankRouteWithChildren
  DashboardWalletWithdrawSuccessRoute: typeof DashboardWalletWithdrawSuccessRoute
  DashboardWalletWithdrawIndexRoute: typeof DashboardWalletWithdrawIndexRoute
}

const DashboardWalletWithdrawRouteChildren: DashboardWalletWithdrawRouteChildren =
  {
    DashboardWalletWithdrawAddBankRoute:
      DashboardWalletWithdrawAddBankRouteWithChildren,
    DashboardWalletWithdrawSuccessRoute: DashboardWalletWithdrawSuccessRoute,
    DashboardWalletWithdrawIndexRoute: DashboardWalletWithdrawIndexRoute,
  }

const DashboardWalletWithdrawRouteWithChildren =
  DashboardWalletWithdrawRoute._addFileChildren(
    DashboardWalletWithdrawRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardCreateRoute: typeof DashboardCreateRoute
  DashboardMeasurementsRoute: typeof DashboardMeasurementsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTailorsRoute: typeof DashboardTailorsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardWalletSpendingRoute: typeof DashboardWalletSpendingRoute
  DashboardWalletTopupRoute: typeof DashboardWalletTopupRouteWithChildren
  DashboardWalletWithdrawRoute: typeof DashboardWalletWithdrawRouteWithChildren
  DashboardExploreIndexRoute: typeof DashboardExploreIndexRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
  DashboardWalletIndexRoute: typeof DashboardWalletIndexRoute
  DashboardOrdersOrderIdAcknowledgeRoute: typeof DashboardOrdersOrderIdAcknowledgeRoute
  DashboardOrdersOrderIdFabricRoute: typeof DashboardOrdersOrderIdFabricRoute
  DashboardOrdersOrderIdPayRoute: typeof DashboardOrdersOrderIdPayRoute
  DashboardOrdersOrderIdRateRoute: typeof DashboardOrdersOrderIdRateRoute
  DashboardWalletTransactionTransactionIdRoute: typeof DashboardWalletTransactionTransactionIdRoute
  DashboardOrdersOrderIdIndexRoute: typeof DashboardOrdersOrderIdIndexRoute
  DashboardExploreMerchantMerchantIdChatRoute: typeof DashboardExploreMerchantMerchantIdChatRoute
  DashboardExploreMerchantMerchantIdPayRoute: typeof DashboardExploreMerchantMerchantIdPayRoute
  DashboardExploreMerchantMerchantIdReviewRoute: typeof DashboardExploreMerchantMerchantIdReviewRoute
  DashboardExploreMerchantMerchantIdSuccessRoute: typeof DashboardExploreMerchantMerchantIdSuccessRoute
  DashboardExploreMerchantMerchantIdTailorsRoute: typeof DashboardExploreMerchantMerchantIdTailorsRoute
  DashboardExploreMerchantMerchantIdIndexRoute: typeof DashboardExploreMerchantMerchantIdIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCreateRoute: DashboardCreateRoute,
  DashboardMeasurementsRoute: DashboardMeasurementsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTailorsRoute: DashboardTailorsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardWalletSpendingRoute: DashboardWalletSpendingRoute,
  DashboardWalletTopupRoute: DashboardWalletTopupRouteWithChildren,
  DashboardWalletWithdrawRoute: DashboardWalletWithdrawRouteWithChildren,
  DashboardExploreIndexRoute: DashboardExploreIndexRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
  DashboardWalletIndexRoute: DashboardWalletIndexRoute,
  DashboardOrdersOrderIdAcknowledgeRoute:
    DashboardOrdersOrderIdAcknowledgeRoute,
  DashboardOrdersOrderIdFabricRoute: DashboardOrdersOrderIdFabricRoute,
  DashboardOrdersOrderIdPayRoute: DashboardOrdersOrderIdPayRoute,
  DashboardOrdersOrderIdRateRoute: DashboardOrdersOrderIdRateRoute,
  DashboardWalletTransactionTransactionIdRoute:
    DashboardWalletTransactionTransactionIdRoute,
  DashboardOrdersOrderIdIndexRoute: DashboardOrdersOrderIdIndexRoute,
  DashboardExploreMerchantMerchantIdChatRoute:
    DashboardExploreMerchantMerchantIdChatRoute,
  DashboardExploreMerchantMerchantIdPayRoute:
    DashboardExploreMerchantMerchantIdPayRoute,
  DashboardExploreMerchantMerchantIdReviewRoute:
    DashboardExploreMerchantMerchantIdReviewRoute,
  DashboardExploreMerchantMerchantIdSuccessRoute:
    DashboardExploreMerchantMerchantIdSuccessRoute,
  DashboardExploreMerchantMerchantIdTailorsRoute:
    DashboardExploreMerchantMerchantIdTailorsRoute,
  DashboardExploreMerchantMerchantIdIndexRoute:
    DashboardExploreMerchantMerchantIdIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
