import type { Tailor } from '@/features/tailors/types'

export const MOCK_TAILORS: Tailor[] = [
  {
    id: '1',
    name: 'Wilfried Mark',
    location: 'Freddy Fashion Fare',
    rating: 4.76,
    reviewCount: 89,
    verified: false,
    specialties: ['Modern', "Men's fit", 'Agbada specialist'],
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=70',
    bio: 'Expert in traditional and modern Nigerian fashion with over 10 years experience.',
    completedOrders: 156,
    responseTime: '1km away',
  },
  {
    id: '2',
    name: 'Aisha Ari',
    location: 'Ari Fashion House',
    rating: 4.95,
    reviewCount: 124,
    verified: true,
    specialties: ['Bridal', 'Ankara', 'Modern'],
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=70',
    bio: 'Specializing in bridal gowns and contemporary African fashion.',
    completedOrders: 203,
    responseTime: '2.5km away',
  },
  {
    id: '3',
    name: 'Freddy Han',
    location: 'Freddy Fashion Fare',
    rating: 4.95,
    reviewCount: 37,
    verified: true,
    specialties: ['Modern', "Men's fit", 'Agbada specialist'],
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&q=70',
    bio: 'Traditional tailor specializing in Agbada and modern menswear.',
    completedOrders: 89,
    responseTime: '3km away',
  },
  {
    id: '4',
    name: 'Yaya Ahmed',
    location: 'Ahmed Couture',
    rating: 4.95,
    reviewCount: 67,
    verified: true,
    specialties: ['Kaftan', 'Modern', 'Traditional'],
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&q=70',
    bio: 'Master craftsman in traditional Nigerian attire and modern fusion.',
    completedOrders: 142,
    responseTime: '4km away',
  },
  {
    id: '5',
    name: 'Nkem Ogbeche',
    location: 'Ogbeche Designs',
    rating: 4.95,
    reviewCount: 98,
    verified: true,
    specialties: ['Bridal', 'Aso Ebi', 'Formal'],
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=70',
    bio: 'Award-winning bridal and formal wear specialist.',
    completedOrders: 178,
    responseTime: '3km away',
  },
  {
    id: '6',
    name: 'Oreoluwa Fasola',
    location: 'Fasola Fabrics',
    rating: 4.95,
    reviewCount: 45,
    verified: true,
    specialties: ['Casual', 'Modern', 'Streetwear'],
    avatar: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400&q=70',
    bio: 'Contemporary African fashion with a modern twist.',
    completedOrders: 91,
    responseTime: '3.6km away',
  },
]
